<?php echo $header; ?>
<!-- Main Content -->
<main>
	<div class="container">
		<div class="countdown">
			<div class="day">
				<p></p>
				<span>Nap</span>
			</div>
			<div class="hour">
				<p></p>
				<span>Óra</span>
			</div>
			<div class="minute">
				<p></p>
				<span>Perc</span>
			</div>
			<div class="second">
				<p></p>
				<span>Másodperc</span>
			</div>
		</div>
	</div>
</main>
<?php echo $footer; ?>
