<footer class="footer">
	<div class="container">
		<nav>
			<ul>
				<li>
					<a href="#">Játékszabályzat</a>
				</li>
				<li>
					<a href="#">Játékhiba bejelentése</a>
				</li>
				<li>
					<a href="#">Impresszum</a>
				</li>
				<li>
					<a href="#">Hírlevél feliratkozás</a>
				</li>
			</ul>
		</nav>
		<div class="follow-us">
			<div class="title">Kövess minket!</div>
			<ul>
				<li><a href="#" class="facebook"></a></li>
				<li><a href="#" class="instagram"></a></li>
				<li><a href="#" class="youtube"></a></li>
			</ul>
		</div>
	</div>
</footer>
<div class="overlay">
	<div class="register-popup form">
		<form method="post">
			<div class="form-control">
				<label for="name">Név</label>
				<input id="name" type="text">
			</div>
			<div class="form-control">
				<label for="reg-email">Email cím</label>
				<input id="reg-email" type="email">
			</div>
			<div class="form-control">
				<label for="reg-password">Jelszó</label>
				<input id="reg-password" type="password">
			</div>
			<input type="submit" value="Mentés">
		</form>
		<a href="#" class="back">mégse</a>
	</div>
	<div class="login-popup form">
		<form method="post">
			<div class="form-control">
				<label for="log-email">Email cím</label>
				<input id="log-email" type="email">
			</div>
			<div class="form-control">
				<label for="log-password">Jelszó</label>
				<input id="log-password" type="password">
			</div>
			<input type="submit" value="Belépés">
		</form>
		<a href="#" class="back">mégse</a>
	</div>
	<div class="profile-popup">
		<a href="#" class="close"></a>
		<div class="name">Májkrémes Nokedli Vájsziti</div>
		<div class="email">erdeteigyöngyiszaggato@gmailöt.com</div>
		<form method="post">
			<div class="form-control clear">
				<div class="left">
					<label for="new-password">Új jelszó</label>
					<input id="new-password" type="password">
				</div>
				<div class="right">
					<label for="e-new-password">Jelszó még egyszer</label>
					<input id="e-new-password" type="password">
				</div>
			</div>
			<input type="submit" value="Mentés">
		</form>
		<div class="own-uploads">
			<div class="title">Feltöltéseim</div>
			<table>
				<tr>
					<td>Dátum</td>
					<td>Trsz</td>
					<td>AP kód</td>
				</tr>
				<tr>
					<td>2016/08/29 - <span>21:36</span></td>
					<td>1234567</td>
					<td>A01234567</td>
				</tr>
				<tr>
					<td>2016/08/29 - <span>21:36</span></td>
					<td>1234567</td>
					<td>A01234567</td>
				</tr>
				<tr>
					<td>2016/08/29 - <span>21:36</span></td>
					<td>1234567</td>
					<td>A01234567</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
	(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
	function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
	e=o.createElement(i);r=o.getElementsByTagName(i)[0];
	e.src='https://www.google-analytics.com/analytics.js';
	r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
	ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>
</body>
</html>